# Generated by Django 2.1.1 on 2018-12-31 16:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='dummy', max_length=200)),
                ('companyAddress', models.CharField(default='dummy', max_length=400)),
                ('companyWebsite', models.URLField(default='google.com')),
                ('rate', models.FloatField(default=1.1)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, default='+98912988888', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='dummy', max_length=20)),
                ('password', models.CharField(default='dummy', max_length=20)),
                ('mail', models.EmailField(default='fmansouri@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSeeker',
            fields=[
                ('name', models.CharField(default='dummy', max_length=200)),
                ('family_name', models.CharField(default='dummy', max_length=200)),
                ('studentID', models.CharField(default='95109253', max_length=8, primary_key=True, serialize=False)),
                ('nationalID', models.CharField(default='1234567891', max_length=10)),
                ('address', models.CharField(default='dummy', max_length=400)),
                ('sex', models.BooleanField(default=0)),
                ('birth_date', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='workSeeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.WorkSeeker'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
    ]
