# Generated by Django 2.1.1 on 2019-01-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='id',
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.User'),
        ),
        migrations.AlterField(
            model_name='workseeker',
            name='studentID',
            field=models.CharField(default='95109253', max_length=8),
        ),
        migrations.AlterField(
            model_name='workseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.User'),
        ),
    ]
